MOBILE-966 Timezone setting removed
phcp/liferay-screens pull request #5
Opened 2018-11-30 17:36 UTC by mclomello

Timezone setting removed because no make sense set this for a date without time definition

2018-12-03 16:26 UTC, phcp requested changes
Thanks for the PR! Please review the suggestions.

2018-12-03 16:26 UTC, phcp commented on android/library/src/main/java/com/liferay/mobile/screens/ddl/model/DateField.java
>                  return simpleDateFormat.parse(stringValue);
SF. It needs an empty space before the line.

2018-12-03 16:26 UTC, phcp commented on android/library/src/main/java/com/liferay/mobile/screens/ddl/model/DateField.java
> -                simpleDateFormat.setTimeZone(TimeZone.getTimeZone("GMT"));
Maybe this class should be refactored, the piece of code above is repeated 4 times.
```
SimpleDateFormat simpleDateFormat = new SimpleDateFormat(<PATTERN>, getCurrentLocale());
return simpleDateFormat.parse(stringValue);
```

2018-12-03 17:01 UTC, victorlaerte requested changes

2018-12-03 17:01 UTC, victorlaerte commented on android/library/src/main/java/com/liferay/mobile/screens/ddl/model/DateField.java
> -                simpleDateFormat.setTimeZone(TimeZone.getTimeZone("GMT"));
Extract in a method

2018-12-05 18:50 UTC, victorlaerte commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2018-12-05 19:15 UTC, victorlaerte approved these changes

2018-12-05 19:18 UTC, victorlaerte commented
Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2018-12-05 19:19 UTC, merged